server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

grpc:
  client:
    __name__:
      negotiation-type: PLAINTEXT
