/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.notification.common.repository.generate.tables.daos;


import com.hieplp.recipe.notification.common.repository.generate.tables.Template;
import com.hieplp.recipe.notification.common.repository.generate.tables.records.TemplateRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TemplateDao extends DAOImpl<TemplateRecord, com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template, Record2<String, Byte>> {

    /**
     * Create a new TemplateDao without any configuration
     */
    public TemplateDao() {
        super(Template.TEMPLATE, com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template.class);
    }

    /**
     * Create a new TemplateDao with an attached configuration
     */
    public TemplateDao(Configuration configuration) {
        super(Template.TEMPLATE, com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template.class, configuration);
    }

    @Override
    public Record2<String, Byte> getId(com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template object) {
        return compositeKeyRecord(object.getAction(), object.getSendvia());
    }

    /**
     * Fetch records that have <code>action BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchRangeOfAction(String lowerInclusive, String upperInclusive) {
        return fetchRange(Template.TEMPLATE.ACTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>action IN (values)</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchByAction(String... values) {
        return fetch(Template.TEMPLATE.ACTION, values);
    }

    /**
     * Fetch records that have <code>sendVia BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchRangeOfSendvia(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Template.TEMPLATE.SENDVIA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sendVia IN (values)</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchBySendvia(Byte... values) {
        return fetch(Template.TEMPLATE.SENDVIA, values);
    }

    /**
     * Fetch records that have <code>subject BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchRangeOfSubject(String lowerInclusive, String upperInclusive) {
        return fetchRange(Template.TEMPLATE.SUBJECT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subject IN (values)</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchBySubject(String... values) {
        return fetch(Template.TEMPLATE.SUBJECT, values);
    }

    /**
     * Fetch records that have <code>content BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchRangeOfContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(Template.TEMPLATE.CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.hieplp.recipe.notification.common.repository.generate.tables.pojos.Template> fetchByContent(String... values) {
        return fetch(Template.TEMPLATE.CONTENT, values);
    }
}
