/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.notification.common.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template implements Serializable {

    private static final long serialVersionUID = 1L;

    private String action;
    private Byte   sendvia;
    private String subject;
    private String content;

    public Template() {}

    public Template(Template value) {
        this.action = value.action;
        this.sendvia = value.sendvia;
        this.subject = value.subject;
        this.content = value.content;
    }

    public Template(
        String action,
        Byte   sendvia,
        String subject,
        String content
    ) {
        this.action = action;
        this.sendvia = sendvia;
        this.subject = subject;
        this.content = content;
    }

    /**
     * Getter for <code>notification.template.action</code>.
     */
    public String getAction() {
        return this.action;
    }

    /**
     * Setter for <code>notification.template.action</code>.
     */
    public Template setAction(String action) {
        this.action = action;
        return this;
    }

    /**
     * Getter for <code>notification.template.sendVia</code>.
     */
    public Byte getSendvia() {
        return this.sendvia;
    }

    /**
     * Setter for <code>notification.template.sendVia</code>.
     */
    public Template setSendvia(Byte sendvia) {
        this.sendvia = sendvia;
        return this;
    }

    /**
     * Getter for <code>notification.template.subject</code>.
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Setter for <code>notification.template.subject</code>.
     */
    public Template setSubject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * Getter for <code>notification.template.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>notification.template.content</code>.
     */
    public Template setContent(String content) {
        this.content = content;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Template (");

        sb.append(action);
        sb.append(", ").append(sendvia);
        sb.append(", ").append(subject);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
