/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables;


import com.hieplp.recipe.user.common.repository.generate.Keys;
import com.hieplp.recipe.user.common.repository.generate.User;
import com.hieplp.recipe.user.common.repository.generate.tables.records.DomainEventEntryRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DomainEventEntry extends TableImpl<DomainEventEntryRecord> {

    /**
     * The reference instance of <code>user.domain_event_entry</code>
     */
    public static final DomainEventEntry DOMAIN_EVENT_ENTRY = new DomainEventEntry();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>user.domain_event_entry.global_index</code>.
     */
    public final TableField<DomainEventEntryRecord, Long> GLOBAL_INDEX = createField(DSL.name("global_index"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.event_identifier</code>.
     */
    public final TableField<DomainEventEntryRecord, String> EVENT_IDENTIFIER = createField(DSL.name("event_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.meta_data</code>.
     */
    public final TableField<DomainEventEntryRecord, byte[]> META_DATA = createField(DSL.name("meta_data"), SQLDataType.BLOB.defaultValue(DSL.inline("NULL", SQLDataType.BLOB)), this, "");
    /**
     * The column <code>user.domain_event_entry.payload</code>.
     */
    public final TableField<DomainEventEntryRecord, byte[]> PAYLOAD = createField(DSL.name("payload"), SQLDataType.BLOB.nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.payload_revision</code>.
     */
    public final TableField<DomainEventEntryRecord, String> PAYLOAD_REVISION = createField(DSL.name("payload_revision"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");
    /**
     * The column <code>user.domain_event_entry.payload_type</code>.
     */
    public final TableField<DomainEventEntryRecord, String> PAYLOAD_TYPE = createField(DSL.name("payload_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.time_stamp</code>.
     */
    public final TableField<DomainEventEntryRecord, String> TIME_STAMP = createField(DSL.name("time_stamp"), SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.aggregate_identifier</code>.
     */
    public final TableField<DomainEventEntryRecord, String> AGGREGATE_IDENTIFIER = createField(DSL.name("aggregate_identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.sequence_number</code>.
     */
    public final TableField<DomainEventEntryRecord, Long> SEQUENCE_NUMBER = createField(DSL.name("sequence_number"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>user.domain_event_entry.type</code>.
     */
    public final TableField<DomainEventEntryRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private DomainEventEntry(Name alias, Table<DomainEventEntryRecord> aliased) {
        this(alias, aliased, null);
    }

    private DomainEventEntry(Name alias, Table<DomainEventEntryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>user.domain_event_entry</code> table reference
     */
    public DomainEventEntry(String alias) {
        this(DSL.name(alias), DOMAIN_EVENT_ENTRY);
    }

    /**
     * Create an aliased <code>user.domain_event_entry</code> table reference
     */
    public DomainEventEntry(Name alias) {
        this(alias, DOMAIN_EVENT_ENTRY);
    }

    /**
     * Create a <code>user.domain_event_entry</code> table reference
     */
    public DomainEventEntry() {
        this(DSL.name("domain_event_entry"), null);
    }

    public <O extends Record> DomainEventEntry(Table<O> child, ForeignKey<O, DomainEventEntryRecord> key) {
        super(child, key, DOMAIN_EVENT_ENTRY);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DomainEventEntryRecord> getRecordType() {
        return DomainEventEntryRecord.class;
    }

    @Override
    public Schema getSchema() {
        return User.USER;
    }

    @Override
    public UniqueKey<DomainEventEntryRecord> getPrimaryKey() {
        return Keys.KEY_DOMAIN_EVENT_ENTRY_PRIMARY;
    }

    @Override
    public List<UniqueKey<DomainEventEntryRecord>> getKeys() {
        return Arrays.<UniqueKey<DomainEventEntryRecord>>asList(Keys.KEY_DOMAIN_EVENT_ENTRY_PRIMARY, Keys.KEY_DOMAIN_EVENT_ENTRY_UK_FWE6LSA8BFO6HYAS6UD3M8C7X, Keys.KEY_DOMAIN_EVENT_ENTRY_UK8S1F994P4LA2IPB13ME2XQM1W);
    }

    @Override
    public DomainEventEntry as(String alias) {
        return new DomainEventEntry(DSL.name(alias), this);
    }

    @Override
    public DomainEventEntry as(Name alias) {
        return new DomainEventEntry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainEventEntry rename(String name) {
        return new DomainEventEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainEventEntry rename(Name name) {
        return new DomainEventEntry(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, byte[], byte[], String, String, String, String, Long, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
