/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.repository.generate;


import com.hieplp.recipe.user.repository.generate.tables.Password;
import com.hieplp.recipe.user.repository.generate.tables.User;
import com.hieplp.recipe.user.repository.generate.tables.records.PasswordRecord;
import com.hieplp.recipe.user.repository.generate.tables.records.UserRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * user.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PasswordRecord> KEY_PASSWORD_PRIMARY = Internal.createUniqueKey(Password.PASSWORD, DSL.name("KEY_password_PRIMARY"), new TableField[]{Password.PASSWORD.USERID}, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER_, DSL.name("KEY_user_PRIMARY"), new TableField[]{User.USER_.USERID}, true);
    public static final UniqueKey<UserRecord> KEY_USER_USERNAME = Internal.createUniqueKey(User.USER_, DSL.name("KEY_user_username"), new TableField[]{User.USER_.USERNAME}, true);
}
