/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.repository.generate;


import com.hieplp.recipe.user.repository.generate.tables.Password;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user</code>
     */
    public static final User USER = new User();

    /**
     * The table <code>user.password</code>.
     */
    public final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>user.user</code>.
     */
    public final com.hieplp.recipe.user.repository.generate.tables.User USER_ = com.hieplp.recipe.user.repository.generate.tables.User.USER_;

    /**
     * No further instances allowed
     */
    private User() {
        super("user", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Password.PASSWORD,
            com.hieplp.recipe.user.repository.generate.tables.User.USER_);
    }
}
