/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AssociationValueEntry implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String associationKey;
    private String associationValue;
    private String sagaId;
    private String sagaType;

    public AssociationValueEntry() {
    }

    public AssociationValueEntry(AssociationValueEntry value) {
        this.id = value.id;
        this.associationKey = value.associationKey;
        this.associationValue = value.associationValue;
        this.sagaId = value.sagaId;
        this.sagaType = value.sagaType;
    }

    public AssociationValueEntry(
            Long id,
            String associationKey,
            String associationValue,
            String sagaId,
            String sagaType
    ) {
        this.id = id;
        this.associationKey = associationKey;
        this.associationValue = associationValue;
        this.sagaId = sagaId;
        this.sagaType = sagaType;
    }

    /**
     * Getter for <code>user.association_value_entry.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>user.association_value_entry.id</code>.
     */
    public AssociationValueEntry setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.association_key</code>.
     */
    public String getAssociationKey() {
        return this.associationKey;
    }

    /**
     * Setter for <code>user.association_value_entry.association_key</code>.
     */
    public AssociationValueEntry setAssociationKey(String associationKey) {
        this.associationKey = associationKey;
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.association_value</code>.
     */
    public String getAssociationValue() {
        return this.associationValue;
    }

    /**
     * Setter for <code>user.association_value_entry.association_value</code>.
     */
    public AssociationValueEntry setAssociationValue(String associationValue) {
        this.associationValue = associationValue;
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.saga_id</code>.
     */
    public String getSagaId() {
        return this.sagaId;
    }

    /**
     * Setter for <code>user.association_value_entry.saga_id</code>.
     */
    public AssociationValueEntry setSagaId(String sagaId) {
        this.sagaId = sagaId;
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.saga_type</code>.
     */
    public String getSagaType() {
        return this.sagaType;
    }

    /**
     * Setter for <code>user.association_value_entry.saga_type</code>.
     */
    public AssociationValueEntry setSagaType(String sagaType) {
        this.sagaType = sagaType;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssociationValueEntry (");

        sb.append(id);
        sb.append(", ").append(associationKey);
        sb.append(", ").append(associationValue);
        sb.append(", ").append(sagaId);
        sb.append(", ").append(sagaType);

        sb.append(")");
        return sb.toString();
    }
}
