/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DeadLetterEntry implements Serializable {

    private static final long serialVersionUID = 1L;

    private String deadLetterId;
    private String causeMessage;
    private String causeType;
    private byte[] diagnostics;
    private LocalDateTime enqueuedAt;
    private LocalDateTime lastTouched;
    private String aggregateIdentifier;
    private String eventIdentifier;
    private String messageType;
    private byte[] metaData;
    private byte[] payload;
    private String payloadRevision;
    private String payloadType;
    private Long sequenceNumber;
    private String timeStamp;
    private byte[] token;
    private String tokenType;
    private String type;
    private String processingGroup;
    private LocalDateTime processingStarted;
    private String sequenceIdentifier;
    private Long sequenceIndex;

    public DeadLetterEntry() {
    }

    public DeadLetterEntry(DeadLetterEntry value) {
        this.deadLetterId = value.deadLetterId;
        this.causeMessage = value.causeMessage;
        this.causeType = value.causeType;
        this.diagnostics = value.diagnostics;
        this.enqueuedAt = value.enqueuedAt;
        this.lastTouched = value.lastTouched;
        this.aggregateIdentifier = value.aggregateIdentifier;
        this.eventIdentifier = value.eventIdentifier;
        this.messageType = value.messageType;
        this.metaData = value.metaData;
        this.payload = value.payload;
        this.payloadRevision = value.payloadRevision;
        this.payloadType = value.payloadType;
        this.sequenceNumber = value.sequenceNumber;
        this.timeStamp = value.timeStamp;
        this.token = value.token;
        this.tokenType = value.tokenType;
        this.type = value.type;
        this.processingGroup = value.processingGroup;
        this.processingStarted = value.processingStarted;
        this.sequenceIdentifier = value.sequenceIdentifier;
        this.sequenceIndex = value.sequenceIndex;
    }

    public DeadLetterEntry(
            String deadLetterId,
            String causeMessage,
            String causeType,
            byte[] diagnostics,
            LocalDateTime enqueuedAt,
            LocalDateTime lastTouched,
            String aggregateIdentifier,
            String eventIdentifier,
            String messageType,
            byte[] metaData,
            byte[] payload,
            String payloadRevision,
            String payloadType,
            Long sequenceNumber,
            String timeStamp,
            byte[] token,
            String tokenType,
            String type,
            String processingGroup,
            LocalDateTime processingStarted,
            String sequenceIdentifier,
            Long sequenceIndex
    ) {
        this.deadLetterId = deadLetterId;
        this.causeMessage = causeMessage;
        this.causeType = causeType;
        this.diagnostics = diagnostics;
        this.enqueuedAt = enqueuedAt;
        this.lastTouched = lastTouched;
        this.aggregateIdentifier = aggregateIdentifier;
        this.eventIdentifier = eventIdentifier;
        this.messageType = messageType;
        this.metaData = metaData;
        this.payload = payload;
        this.payloadRevision = payloadRevision;
        this.payloadType = payloadType;
        this.sequenceNumber = sequenceNumber;
        this.timeStamp = timeStamp;
        this.token = token;
        this.tokenType = tokenType;
        this.type = type;
        this.processingGroup = processingGroup;
        this.processingStarted = processingStarted;
        this.sequenceIdentifier = sequenceIdentifier;
        this.sequenceIndex = sequenceIndex;
    }

    /**
     * Getter for <code>user.dead_letter_entry.dead_letter_id</code>.
     */
    public String getDeadLetterId() {
        return this.deadLetterId;
    }

    /**
     * Setter for <code>user.dead_letter_entry.dead_letter_id</code>.
     */
    public DeadLetterEntry setDeadLetterId(String deadLetterId) {
        this.deadLetterId = deadLetterId;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.cause_message</code>.
     */
    public String getCauseMessage() {
        return this.causeMessage;
    }

    /**
     * Setter for <code>user.dead_letter_entry.cause_message</code>.
     */
    public DeadLetterEntry setCauseMessage(String causeMessage) {
        this.causeMessage = causeMessage;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.cause_type</code>.
     */
    public String getCauseType() {
        return this.causeType;
    }

    /**
     * Setter for <code>user.dead_letter_entry.cause_type</code>.
     */
    public DeadLetterEntry setCauseType(String causeType) {
        this.causeType = causeType;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.diagnostics</code>.
     */
    public byte[] getDiagnostics() {
        return this.diagnostics;
    }

    /**
     * Setter for <code>user.dead_letter_entry.diagnostics</code>.
     */
    public DeadLetterEntry setDiagnostics(byte[] diagnostics) {
        this.diagnostics = diagnostics;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.enqueued_at</code>.
     */
    public LocalDateTime getEnqueuedAt() {
        return this.enqueuedAt;
    }

    /**
     * Setter for <code>user.dead_letter_entry.enqueued_at</code>.
     */
    public DeadLetterEntry setEnqueuedAt(LocalDateTime enqueuedAt) {
        this.enqueuedAt = enqueuedAt;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.last_touched</code>.
     */
    public LocalDateTime getLastTouched() {
        return this.lastTouched;
    }

    /**
     * Setter for <code>user.dead_letter_entry.last_touched</code>.
     */
    public DeadLetterEntry setLastTouched(LocalDateTime lastTouched) {
        this.lastTouched = lastTouched;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.aggregate_identifier</code>.
     */
    public String getAggregateIdentifier() {
        return this.aggregateIdentifier;
    }

    /**
     * Setter for <code>user.dead_letter_entry.aggregate_identifier</code>.
     */
    public DeadLetterEntry setAggregateIdentifier(String aggregateIdentifier) {
        this.aggregateIdentifier = aggregateIdentifier;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.event_identifier</code>.
     */
    public String getEventIdentifier() {
        return this.eventIdentifier;
    }

    /**
     * Setter for <code>user.dead_letter_entry.event_identifier</code>.
     */
    public DeadLetterEntry setEventIdentifier(String eventIdentifier) {
        this.eventIdentifier = eventIdentifier;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.message_type</code>.
     */
    public String getMessageType() {
        return this.messageType;
    }

    /**
     * Setter for <code>user.dead_letter_entry.message_type</code>.
     */
    public DeadLetterEntry setMessageType(String messageType) {
        this.messageType = messageType;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.meta_data</code>.
     */
    public byte[] getMetaData() {
        return this.metaData;
    }

    /**
     * Setter for <code>user.dead_letter_entry.meta_data</code>.
     */
    public DeadLetterEntry setMetaData(byte[] metaData) {
        this.metaData = metaData;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.payload</code>.
     */
    public byte[] getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>user.dead_letter_entry.payload</code>.
     */
    public DeadLetterEntry setPayload(byte[] payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.payload_revision</code>.
     */
    public String getPayloadRevision() {
        return this.payloadRevision;
    }

    /**
     * Setter for <code>user.dead_letter_entry.payload_revision</code>.
     */
    public DeadLetterEntry setPayloadRevision(String payloadRevision) {
        this.payloadRevision = payloadRevision;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.payload_type</code>.
     */
    public String getPayloadType() {
        return this.payloadType;
    }

    /**
     * Setter for <code>user.dead_letter_entry.payload_type</code>.
     */
    public DeadLetterEntry setPayloadType(String payloadType) {
        this.payloadType = payloadType;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.sequence_number</code>.
     */
    public Long getSequenceNumber() {
        return this.sequenceNumber;
    }

    /**
     * Setter for <code>user.dead_letter_entry.sequence_number</code>.
     */
    public DeadLetterEntry setSequenceNumber(Long sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.time_stamp</code>.
     */
    public String getTimeStamp() {
        return this.timeStamp;
    }

    /**
     * Setter for <code>user.dead_letter_entry.time_stamp</code>.
     */
    public DeadLetterEntry setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.token</code>.
     */
    public byte[] getToken() {
        return this.token;
    }

    /**
     * Setter for <code>user.dead_letter_entry.token</code>.
     */
    public DeadLetterEntry setToken(byte[] token) {
        this.token = token;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.token_type</code>.
     */
    public String getTokenType() {
        return this.tokenType;
    }

    /**
     * Setter for <code>user.dead_letter_entry.token_type</code>.
     */
    public DeadLetterEntry setTokenType(String tokenType) {
        this.tokenType = tokenType;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>user.dead_letter_entry.type</code>.
     */
    public DeadLetterEntry setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.processing_group</code>.
     */
    public String getProcessingGroup() {
        return this.processingGroup;
    }

    /**
     * Setter for <code>user.dead_letter_entry.processing_group</code>.
     */
    public DeadLetterEntry setProcessingGroup(String processingGroup) {
        this.processingGroup = processingGroup;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.processing_started</code>.
     */
    public LocalDateTime getProcessingStarted() {
        return this.processingStarted;
    }

    /**
     * Setter for <code>user.dead_letter_entry.processing_started</code>.
     */
    public DeadLetterEntry setProcessingStarted(LocalDateTime processingStarted) {
        this.processingStarted = processingStarted;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.sequence_identifier</code>.
     */
    public String getSequenceIdentifier() {
        return this.sequenceIdentifier;
    }

    /**
     * Setter for <code>user.dead_letter_entry.sequence_identifier</code>.
     */
    public DeadLetterEntry setSequenceIdentifier(String sequenceIdentifier) {
        this.sequenceIdentifier = sequenceIdentifier;
        return this;
    }

    /**
     * Getter for <code>user.dead_letter_entry.sequence_index</code>.
     */
    public Long getSequenceIndex() {
        return this.sequenceIndex;
    }

    /**
     * Setter for <code>user.dead_letter_entry.sequence_index</code>.
     */
    public DeadLetterEntry setSequenceIndex(Long sequenceIndex) {
        this.sequenceIndex = sequenceIndex;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeadLetterEntry (");

        sb.append(deadLetterId);
        sb.append(", ").append(causeMessage);
        sb.append(", ").append(causeType);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(enqueuedAt);
        sb.append(", ").append(lastTouched);
        sb.append(", ").append(aggregateIdentifier);
        sb.append(", ").append(eventIdentifier);
        sb.append(", ").append(messageType);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(payloadRevision);
        sb.append(", ").append(payloadType);
        sb.append(", ").append(sequenceNumber);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(tokenType);
        sb.append(", ").append(type);
        sb.append(", ").append(processingGroup);
        sb.append(", ").append(processingStarted);
        sb.append(", ").append(sequenceIdentifier);
        sb.append(", ").append(sequenceIndex);

        sb.append(")");
        return sb.toString();
    }
}
