/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DomainEventEntry implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long globalIndex;
    private String eventIdentifier;
    private byte[] metaData;
    private byte[] payload;
    private String payloadRevision;
    private String payloadType;
    private String timeStamp;
    private String aggregateIdentifier;
    private Long sequenceNumber;
    private String type;

    public DomainEventEntry() {
    }

    public DomainEventEntry(DomainEventEntry value) {
        this.globalIndex = value.globalIndex;
        this.eventIdentifier = value.eventIdentifier;
        this.metaData = value.metaData;
        this.payload = value.payload;
        this.payloadRevision = value.payloadRevision;
        this.payloadType = value.payloadType;
        this.timeStamp = value.timeStamp;
        this.aggregateIdentifier = value.aggregateIdentifier;
        this.sequenceNumber = value.sequenceNumber;
        this.type = value.type;
    }

    public DomainEventEntry(
            Long globalIndex,
            String eventIdentifier,
            byte[] metaData,
            byte[] payload,
            String payloadRevision,
            String payloadType,
            String timeStamp,
            String aggregateIdentifier,
            Long sequenceNumber,
            String type
    ) {
        this.globalIndex = globalIndex;
        this.eventIdentifier = eventIdentifier;
        this.metaData = metaData;
        this.payload = payload;
        this.payloadRevision = payloadRevision;
        this.payloadType = payloadType;
        this.timeStamp = timeStamp;
        this.aggregateIdentifier = aggregateIdentifier;
        this.sequenceNumber = sequenceNumber;
        this.type = type;
    }

    /**
     * Getter for <code>user.domain_event_entry.global_index</code>.
     */
    public Long getGlobalIndex() {
        return this.globalIndex;
    }

    /**
     * Setter for <code>user.domain_event_entry.global_index</code>.
     */
    public DomainEventEntry setGlobalIndex(Long globalIndex) {
        this.globalIndex = globalIndex;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.event_identifier</code>.
     */
    public String getEventIdentifier() {
        return this.eventIdentifier;
    }

    /**
     * Setter for <code>user.domain_event_entry.event_identifier</code>.
     */
    public DomainEventEntry setEventIdentifier(String eventIdentifier) {
        this.eventIdentifier = eventIdentifier;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.meta_data</code>.
     */
    public byte[] getMetaData() {
        return this.metaData;
    }

    /**
     * Setter for <code>user.domain_event_entry.meta_data</code>.
     */
    public DomainEventEntry setMetaData(byte[] metaData) {
        this.metaData = metaData;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload</code>.
     */
    public byte[] getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>user.domain_event_entry.payload</code>.
     */
    public DomainEventEntry setPayload(byte[] payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload_revision</code>.
     */
    public String getPayloadRevision() {
        return this.payloadRevision;
    }

    /**
     * Setter for <code>user.domain_event_entry.payload_revision</code>.
     */
    public DomainEventEntry setPayloadRevision(String payloadRevision) {
        this.payloadRevision = payloadRevision;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload_type</code>.
     */
    public String getPayloadType() {
        return this.payloadType;
    }

    /**
     * Setter for <code>user.domain_event_entry.payload_type</code>.
     */
    public DomainEventEntry setPayloadType(String payloadType) {
        this.payloadType = payloadType;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.time_stamp</code>.
     */
    public String getTimeStamp() {
        return this.timeStamp;
    }

    /**
     * Setter for <code>user.domain_event_entry.time_stamp</code>.
     */
    public DomainEventEntry setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.aggregate_identifier</code>.
     */
    public String getAggregateIdentifier() {
        return this.aggregateIdentifier;
    }

    /**
     * Setter for <code>user.domain_event_entry.aggregate_identifier</code>.
     */
    public DomainEventEntry setAggregateIdentifier(String aggregateIdentifier) {
        this.aggregateIdentifier = aggregateIdentifier;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.sequence_number</code>.
     */
    public Long getSequenceNumber() {
        return this.sequenceNumber;
    }

    /**
     * Setter for <code>user.domain_event_entry.sequence_number</code>.
     */
    public DomainEventEntry setSequenceNumber(Long sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>user.domain_event_entry.type</code>.
     */
    public DomainEventEntry setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DomainEventEntry (");

        sb.append(globalIndex);
        sb.append(", ").append(eventIdentifier);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(payloadRevision);
        sb.append(", ").append(payloadType);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(aggregateIdentifier);
        sb.append(", ").append(sequenceNumber);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
