/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HibernateSequence implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long nextVal;

    public HibernateSequence() {
    }

    public HibernateSequence(HibernateSequence value) {
        this.nextVal = value.nextVal;
    }

    public HibernateSequence(
            Long nextVal
    ) {
        this.nextVal = nextVal;
    }

    /**
     * Getter for <code>user.hibernate_sequence.next_val</code>.
     */
    public Long getNextVal() {
        return this.nextVal;
    }

    /**
     * Setter for <code>user.hibernate_sequence.next_val</code>.
     */
    public HibernateSequence setNextVal(Long nextVal) {
        this.nextVal = nextVal;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HibernateSequence (");

        sb.append(nextVal);

        sb.append(")");
        return sb.toString();
    }
}
