/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.repository.generate;


import com.hieplp.recipe.auth.repository.generate.tables.Otp;


/**
 * Convenience access to all tables in authentication.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>authentication.otp</code>.
     */
    public static final Otp OTP = Otp.OTP;
}
