/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Otp implements Serializable {

    private static final long serialVersionUID = 1L;

    private String otpid;
    private String sendto;
    private String otpcode;
    private Byte status;
    private LocalDateTime issuedat;
    private LocalDateTime expiredat;
    private LocalDateTime createdat;
    private String createdby;
    private LocalDateTime modifiedat;
    private String modifiedby;

    public Otp() {
    }

    public Otp(Otp value) {
        this.otpid = value.otpid;
        this.sendto = value.sendto;
        this.otpcode = value.otpcode;
        this.status = value.status;
        this.issuedat = value.issuedat;
        this.expiredat = value.expiredat;
        this.createdat = value.createdat;
        this.createdby = value.createdby;
        this.modifiedat = value.modifiedat;
        this.modifiedby = value.modifiedby;
    }

    public Otp(
            String otpid,
            String sendto,
            String otpcode,
            Byte status,
            LocalDateTime issuedat,
            LocalDateTime expiredat,
            LocalDateTime createdat,
            String createdby,
            LocalDateTime modifiedat,
            String modifiedby
    ) {
        this.otpid = otpid;
        this.sendto = sendto;
        this.otpcode = otpcode;
        this.status = status;
        this.issuedat = issuedat;
        this.expiredat = expiredat;
        this.createdat = createdat;
        this.createdby = createdby;
        this.modifiedat = modifiedat;
        this.modifiedby = modifiedby;
    }

    /**
     * Getter for <code>authentication.otp.otpId</code>.
     */
    public String getOtpid() {
        return this.otpid;
    }

    /**
     * Setter for <code>authentication.otp.otpId</code>.
     */
    public Otp setOtpid(String otpid) {
        this.otpid = otpid;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.sendTo</code>.
     */
    public String getSendto() {
        return this.sendto;
    }

    /**
     * Setter for <code>authentication.otp.sendTo</code>.
     */
    public Otp setSendto(String sendto) {
        this.sendto = sendto;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.otpCode</code>.
     */
    public String getOtpcode() {
        return this.otpcode;
    }

    /**
     * Setter for <code>authentication.otp.otpCode</code>.
     */
    public Otp setOtpcode(String otpcode) {
        this.otpcode = otpcode;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>authentication.otp.status</code>.
     */
    public Otp setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.issuedAt</code>.
     */
    public LocalDateTime getIssuedat() {
        return this.issuedat;
    }

    /**
     * Setter for <code>authentication.otp.issuedAt</code>.
     */
    public Otp setIssuedat(LocalDateTime issuedat) {
        this.issuedat = issuedat;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.expiredAt</code>.
     */
    public LocalDateTime getExpiredat() {
        return this.expiredat;
    }

    /**
     * Setter for <code>authentication.otp.expiredAt</code>.
     */
    public Otp setExpiredat(LocalDateTime expiredat) {
        this.expiredat = expiredat;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>authentication.otp.createdAt</code>.
     */
    public Otp setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>authentication.otp.createdBy</code>.
     */
    public Otp setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>authentication.otp.modifiedAt</code>.
     */
    public Otp setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    /**
     * Getter for <code>authentication.otp.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>authentication.otp.modifiedBy</code>.
     */
    public Otp setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Otp (");

        sb.append(otpid);
        sb.append(", ").append(sendto);
        sb.append(", ").append(otpcode);
        sb.append(", ").append(status);
        sb.append(", ").append(issuedat);
        sb.append(", ").append(expiredat);
        sb.append(", ").append(createdat);
        sb.append(", ").append(createdby);
        sb.append(", ").append(modifiedat);
        sb.append(", ").append(modifiedby);

        sb.append(")");
        return sb.toString();
    }
}
