/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        userid;
    private String        username;
    private String        fullname;
    private String        email;
    private Byte          status;
    private byte[]        password;
    private byte[]        salt;
    private String        createdby;
    private LocalDateTime createdat;
    private String        modifiedby;
    private LocalDateTime modifiedat;

    public TempUser() {}

    public TempUser(TempUser value) {
        this.userid = value.userid;
        this.username = value.username;
        this.fullname = value.fullname;
        this.email = value.email;
        this.status = value.status;
        this.password = value.password;
        this.salt = value.salt;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
    }

    public TempUser(
        String        userid,
        String        username,
        String        fullname,
        String        email,
        Byte          status,
        byte[]        password,
        byte[]        salt,
        String        createdby,
        LocalDateTime createdat,
        String        modifiedby,
        LocalDateTime modifiedat
    ) {
        this.userid = userid;
        this.username = username;
        this.fullname = fullname;
        this.email = email;
        this.status = status;
        this.password = password;
        this.salt = salt;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>authentication.temp_user.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>authentication.temp_user.userId</code>.
     */
    public TempUser setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>authentication.temp_user.username</code>.
     */
    public TempUser setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.fullName</code>.
     */
    public String getFullname() {
        return this.fullname;
    }

    /**
     * Setter for <code>authentication.temp_user.fullName</code>.
     */
    public TempUser setFullname(String fullname) {
        this.fullname = fullname;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>authentication.temp_user.email</code>.
     */
    public TempUser setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>authentication.temp_user.status</code>.
     */
    public TempUser setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.password</code>.
     */
    public byte[] getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>authentication.temp_user.password</code>.
     */
    public TempUser setPassword(byte[] password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.salt</code>.
     */
    public byte[] getSalt() {
        return this.salt;
    }

    /**
     * Setter for <code>authentication.temp_user.salt</code>.
     */
    public TempUser setSalt(byte[] salt) {
        this.salt = salt;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>authentication.temp_user.createdBy</code>.
     */
    public TempUser setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>authentication.temp_user.createdAt</code>.
     */
    public TempUser setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>authentication.temp_user.modifiedBy</code>.
     */
    public TempUser setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>authentication.temp_user.modifiedAt</code>.
     */
    public TempUser setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TempUser (");

        sb.append(userid);
        sb.append(", ").append(username);
        sb.append(", ").append(fullname);
        sb.append(", ").append(email);
        sb.append(", ").append(status);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
