/*
 * This file is generated by jOOQ.
 */
package com.hieplp.service.user.repository.generate;


import com.hieplp.service.user.repository.generate.tables.Password;
import com.hieplp.service.user.repository.generate.tables.User;


/**
 * Convenience access to all tables in user.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>user.password</code>.
     */
    public static final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>user.user</code>.
     */
    public static final User USER_ = User.USER_;
}
