/*
 * This file is generated by jOOQ.
 */
package com.hieplp.service.user.repository.generate;


import com.hieplp.service.user.repository.generate.tables.Password;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User extends SchemaImpl {

    /**
     * The reference instance of <code>user</code>
     */
    public static final User USER = new User();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>user.password</code>.
     */
    public final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>user.user</code>.
     */
    public final com.hieplp.service.user.repository.generate.tables.User USER_ = com.hieplp.service.user.repository.generate.tables.User.USER_;

    /**
     * No further instances allowed
     */
    private User() {
        super("user", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Password.PASSWORD,
                com.hieplp.service.user.repository.generate.tables.User.USER_);
    }
}
