/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate;


import com.hieplp.recipe.auth.common.repository.generate.tables.Otp;
import com.hieplp.recipe.auth.common.repository.generate.tables.TempUser;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Authentication extends SchemaImpl {

    /**
     * The reference instance of <code>authentication</code>
     */
    public static final Authentication AUTHENTICATION = new Authentication();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>authentication.otp</code>.
     */
    public final Otp OTP = Otp.OTP;

    /**
     * The table <code>authentication.temp_user</code>.
     */
    public final TempUser TEMP_USER = TempUser.TEMP_USER;

    /**
     * No further instances allowed
     */
    private Authentication() {
        super("authentication", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Otp.OTP,
                TempUser.TEMP_USER);
    }
}
