/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate;


import com.hieplp.recipe.auth.common.repository.generate.tables.Otp;
import com.hieplp.recipe.auth.common.repository.generate.tables.TempUser;


/**
 * Convenience access to all tables in authentication.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>authentication.otp</code>.
     */
    public static final Otp OTP = Otp.OTP;

    /**
     * The table <code>authentication.temp_user</code>.
     */
    public static final TempUser TEMP_USER = TempUser.TEMP_USER;
}
