/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.notification.common.repository.generate.tables.records;


import com.hieplp.recipe.notification.common.repository.generate.tables.Log;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LogRecord extends UpdatableRecordImpl<LogRecord> implements Record12<String, String, Byte, String, String, String, Byte, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(String logid, String action, Byte sendvia, String subject, String content, String sendto, Byte status, String referenceid, String createdby, LocalDateTime createdat, String modifiedby, LocalDateTime modifiedat) {
        super(Log.LOG);

        setLogid(logid);
        setAction(action);
        setSendvia(sendvia);
        setSubject(subject);
        setContent(content);
        setSendto(sendto);
        setStatus(status);
        setReferenceid(referenceid);
        setCreatedby(createdby);
        setCreatedat(createdat);
        setModifiedby(modifiedby);
        setModifiedat(modifiedat);
    }

    /**
     * Getter for <code>notification.log.logId</code>.
     */
    public String getLogid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>notification.log.logId</code>.
     */
    public LogRecord setLogid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notification.log.action</code>.
     */
    public LogRecord setAction(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.sendVia</code>.
     */
    public Byte getSendvia() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>notification.log.sendVia</code>.
     */
    public LogRecord setSendvia(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.subject</code>.
     */
    public String getSubject() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notification.log.subject</code>.
     */
    public LogRecord setSubject(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notification.log.content</code>.
     */
    public LogRecord setContent(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.sendTo</code>.
     */
    public String getSendto() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notification.log.sendTo</code>.
     */
    public LogRecord setSendto(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>notification.log.status</code>.
     */
    public LogRecord setStatus(Byte value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.referenceId</code>.
     */
    public String getReferenceid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>notification.log.referenceId</code>.
     */
    public LogRecord setReferenceid(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.createdBy</code>.
     */
    public String getCreatedby() {
        return (String) get(8);
    }

    /**
     * Setter for <code>notification.log.createdBy</code>.
     */
    public LogRecord setCreatedby(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>notification.log.createdAt</code>.
     */
    public LogRecord setCreatedat(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>notification.log.modifiedBy</code>.
     */
    public String getModifiedby() {
        return (String) get(10);
    }

    /**
     * Setter for <code>notification.log.modifiedBy</code>.
     */
    public LogRecord setModifiedby(String value) {
        set(10, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>notification.log.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>notification.log.modifiedAt</code>.
     */
    public LogRecord setModifiedat(LocalDateTime value) {
        set(11, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row12<String, String, Byte, String, String, String, Byte, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, Byte, String, String, String, Byte, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Log.LOG.LOGID;
    }

    @Override
    public Field<String> field2() {
        return Log.LOG.ACTION;
    }

    @Override
    public Field<Byte> field3() {
        return Log.LOG.SENDVIA;
    }

    @Override
    public Field<String> field4() {
        return Log.LOG.SUBJECT;
    }

    @Override
    public Field<String> field5() {
        return Log.LOG.CONTENT;
    }

    @Override
    public Field<String> field6() {
        return Log.LOG.SENDTO;
    }

    @Override
    public Field<Byte> field7() {
        return Log.LOG.STATUS;
    }

    @Override
    public Field<String> field8() {
        return Log.LOG.REFERENCEID;
    }

    @Override
    public Field<String> field9() {
        return Log.LOG.CREATEDBY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Log.LOG.CREATEDAT;
    }

    @Override
    public Field<String> field11() {
        return Log.LOG.MODIFIEDBY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Log.LOG.MODIFIEDAT;
    }

    @Override
    public String component1() {
        return getLogid();
    }

    @Override
    public String component2() {
        return getAction();
    }

    @Override
    public Byte component3() {
        return getSendvia();
    }

    @Override
    public String component4() {
        return getSubject();
    }

    @Override
    public String component5() {
        return getContent();
    }

    @Override
    public String component6() {
        return getSendto();
    }

    @Override
    public Byte component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getReferenceid();
    }

    @Override
    public String component9() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedat();
    }

    @Override
    public String component11() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime component12() {
        return getModifiedat();
    }

    @Override
    public String value1() {
        return getLogid();
    }

    @Override
    public String value2() {
        return getAction();
    }

    @Override
    public Byte value3() {
        return getSendvia();
    }

    @Override
    public String value4() {
        return getSubject();
    }

    @Override
    public String value5() {
        return getContent();
    }

    @Override
    public String value6() {
        return getSendto();
    }

    @Override
    public Byte value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getReferenceid();
    }

    @Override
    public String value9() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedat();
    }

    @Override
    public String value11() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime value12() {
        return getModifiedat();
    }

    @Override
    public LogRecord value1(String value) {
        setLogid(value);
        return this;
    }

    @Override
    public LogRecord value2(String value) {
        setAction(value);
        return this;
    }

    @Override
    public LogRecord value3(Byte value) {
        setSendvia(value);
        return this;
    }

    @Override
    public LogRecord value4(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public LogRecord value5(String value) {
        setContent(value);
        return this;
    }

    @Override
    public LogRecord value6(String value) {
        setSendto(value);
        return this;
    }

    @Override
    public LogRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public LogRecord value8(String value) {
        setReferenceid(value);
        return this;
    }

    @Override
    public LogRecord value9(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public LogRecord value10(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public LogRecord value11(String value) {
        setModifiedby(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public LogRecord value12(LocalDateTime value) {
        setModifiedat(value);
        return this;
    }

    @Override
    public LogRecord values(String value1, String value2, Byte value3, String value4, String value5, String value6, Byte value7, String value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }
}
