server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/user
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jooq:
    sql-dialect: mariadb
  mvc:
    converters:
      preferred-json-mapper: gson

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#grpc:
#  server:
#    security:
#      enabled: true
#      certificate-chain: file:certificates/server.crt
#      private-key: file:certificates/server.key