/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.daos;


import com.hieplp.recipe.user.common.repository.generate.tables.Password;
import com.hieplp.recipe.user.common.repository.generate.tables.records.PasswordRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PasswordDao extends DAOImpl<PasswordRecord, com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password, String> {

    /**
     * Create a new PasswordDao without any configuration
     */
    public PasswordDao() {
        super(Password.PASSWORD, com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password.class);
    }

    /**
     * Create a new PasswordDao with an attached configuration
     */
    public PasswordDao(Configuration configuration) {
        super(Password.PASSWORD, com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password.class, configuration);
    }

    @Override
    public String getId(com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password object) {
        return object.getUserid();
    }

    /**
     * Fetch records that have <code>userId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfUserid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Password.PASSWORD.USERID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByUserid(String... values) {
        return fetch(Password.PASSWORD.USERID, values);
    }

    /**
     * Fetch a unique record that has <code>userId = value</code>
     */
    public com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password fetchOneByUserid(String value) {
        return fetchOne(Password.PASSWORD.USERID, value);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfPassword(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Password.PASSWORD.PASSWORD_, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByPassword(byte[]... values) {
        return fetch(Password.PASSWORD.PASSWORD_, values);
    }

    /**
     * Fetch records that have <code>salt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfSalt(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(Password.PASSWORD.SALT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchBySalt(byte[]... values) {
        return fetch(Password.PASSWORD.SALT, values);
    }

    /**
     * Fetch records that have <code>createdBy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Password.PASSWORD.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdBy IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByCreatedby(String... values) {
        return fetch(Password.PASSWORD.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>createdAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfCreatedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Password.PASSWORD.CREATEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdAt IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByCreatedat(LocalDateTime... values) {
        return fetch(Password.PASSWORD.CREATEDAT, values);
    }

    /**
     * Fetch records that have <code>modifiedBy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfModifiedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Password.PASSWORD.MODIFIEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedBy IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByModifiedby(String... values) {
        return fetch(Password.PASSWORD.MODIFIEDBY, values);
    }

    /**
     * Fetch records that have <code>modifiedAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchRangeOfModifiedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Password.PASSWORD.MODIFIEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedAt IN (values)</code>
     */
    public List<com.hieplp.recipe.user.common.repository.generate.tables.pojos.Password> fetchByModifiedat(LocalDateTime... values) {
        return fetch(Password.PASSWORD.MODIFIEDAT, values);
    }
}
