/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.notification.common.repository.generate;


import com.hieplp.recipe.notification.common.repository.generate.tables.Log;
import com.hieplp.recipe.notification.common.repository.generate.tables.Template;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Notification extends SchemaImpl {

    /**
     * The reference instance of <code>notification</code>
     */
    public static final Notification NOTIFICATION = new Notification();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>notification.log</code>.
     */
    public final Log LOG = Log.LOG;

    /**
     * The table <code>notification.template</code>.
     */
    public final Template TEMPLATE = Template.TEMPLATE;

    /**
     * No further instances allowed
     */
    private Notification() {
        super("notification", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Log.LOG,
                Template.TEMPLATE);
    }
}
