/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.notification.common.repository.generate;


import com.hieplp.recipe.notification.common.repository.generate.tables.Log;
import com.hieplp.recipe.notification.common.repository.generate.tables.Template;


/**
 * Convenience access to all tables in notification.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>notification.log</code>.
     */
    public static final Log LOG = Log.LOG;

    /**
     * The table <code>notification.template</code>.
     */
    public static final Template TEMPLATE = Template.TEMPLATE;
}
