/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables.records;


import com.hieplp.recipe.auth.common.repository.generate.tables.Otphistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OtphistoryRecord extends UpdatableRecordImpl<OtphistoryRecord> implements Record9<String, String, String, Byte, Byte, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached OtphistoryRecord
     */
    public OtphistoryRecord() {
        super(Otphistory.OTPHISTORY);
    }

    /**
     * Create a detached, initialised OtphistoryRecord
     */
    public OtphistoryRecord(String otphistoryid, String otpid, String otpcode, Byte status, Byte type, String createdby, LocalDateTime createdat, String modifiedby, LocalDateTime modifiedat) {
        super(Otphistory.OTPHISTORY);

        setOtphistoryid(otphistoryid);
        setOtpid(otpid);
        setOtpcode(otpcode);
        setStatus(status);
        setType(type);
        setCreatedby(createdby);
        setCreatedat(createdat);
        setModifiedby(modifiedby);
        setModifiedat(modifiedat);
    }

    /**
     * Getter for <code>authentication.otpHistory.otpHistoryId</code>.
     */
    public String getOtphistoryid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>authentication.otpHistory.otpHistoryId</code>.
     */
    public OtphistoryRecord setOtphistoryid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.otpId</code>.
     */
    public String getOtpid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>authentication.otpHistory.otpId</code>.
     */
    public OtphistoryRecord setOtpid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.otpCode</code>.
     */
    public String getOtpcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>authentication.otpHistory.otpCode</code>.
     */
    public OtphistoryRecord setOtpcode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>authentication.otpHistory.status</code>.
     */
    public OtphistoryRecord setStatus(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.type</code>.
     */
    public Byte getType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>authentication.otpHistory.type</code>.
     */
    public OtphistoryRecord setType(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.createdBy</code>.
     */
    public String getCreatedby() {
        return (String) get(5);
    }

    /**
     * Setter for <code>authentication.otpHistory.createdBy</code>.
     */
    public OtphistoryRecord setCreatedby(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>authentication.otpHistory.createdAt</code>.
     */
    public OtphistoryRecord setCreatedat(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>authentication.otpHistory.modifiedBy</code>.
     */
    public String getModifiedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>authentication.otpHistory.modifiedBy</code>.
     */
    public OtphistoryRecord setModifiedby(String value) {
        set(7, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>authentication.otpHistory.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>authentication.otpHistory.modifiedAt</code>.
     */
    public OtphistoryRecord setModifiedat(LocalDateTime value) {
        set(8, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row9<String, String, String, Byte, Byte, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, Byte, Byte, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Otphistory.OTPHISTORY.OTPHISTORYID;
    }

    @Override
    public Field<String> field2() {
        return Otphistory.OTPHISTORY.OTPID;
    }

    @Override
    public Field<String> field3() {
        return Otphistory.OTPHISTORY.OTPCODE;
    }

    @Override
    public Field<Byte> field4() {
        return Otphistory.OTPHISTORY.STATUS;
    }

    @Override
    public Field<Byte> field5() {
        return Otphistory.OTPHISTORY.TYPE;
    }

    @Override
    public Field<String> field6() {
        return Otphistory.OTPHISTORY.CREATEDBY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Otphistory.OTPHISTORY.CREATEDAT;
    }

    @Override
    public Field<String> field8() {
        return Otphistory.OTPHISTORY.MODIFIEDBY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Otphistory.OTPHISTORY.MODIFIEDAT;
    }

    @Override
    public String component1() {
        return getOtphistoryid();
    }

    @Override
    public String component2() {
        return getOtpid();
    }

    @Override
    public String component3() {
        return getOtpcode();
    }

    @Override
    public Byte component4() {
        return getStatus();
    }

    @Override
    public Byte component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedat();
    }

    @Override
    public String component8() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedat();
    }

    @Override
    public String value1() {
        return getOtphistoryid();
    }

    @Override
    public String value2() {
        return getOtpid();
    }

    @Override
    public String value3() {
        return getOtpcode();
    }

    @Override
    public Byte value4() {
        return getStatus();
    }

    @Override
    public Byte value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedat();
    }

    @Override
    public String value8() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedat();
    }

    @Override
    public OtphistoryRecord value1(String value) {
        setOtphistoryid(value);
        return this;
    }

    @Override
    public OtphistoryRecord value2(String value) {
        setOtpid(value);
        return this;
    }

    @Override
    public OtphistoryRecord value3(String value) {
        setOtpcode(value);
        return this;
    }

    @Override
    public OtphistoryRecord value4(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public OtphistoryRecord value5(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public OtphistoryRecord value6(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public OtphistoryRecord value7(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public OtphistoryRecord value8(String value) {
        setModifiedby(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public OtphistoryRecord value9(LocalDateTime value) {
        setModifiedat(value);
        return this;
    }

    @Override
    public OtphistoryRecord values(String value1, String value2, String value3, Byte value4, Byte value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
