/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables.records;


import com.hieplp.recipe.auth.common.repository.generate.tables.TempUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TempUserRecord extends UpdatableRecordImpl<TempUserRecord> implements Record12<String, String, String, String, String, Byte, byte[], byte[], String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached TempUserRecord
     */
    public TempUserRecord() {
        super(TempUser.TEMP_USER);
    }

    /**
     * Create a detached, initialised TempUserRecord
     */
    public TempUserRecord(String userid, String otpid, String username, String fullname, String email, Byte status, byte[] password, byte[] salt, String createdby, LocalDateTime createdat, String modifiedby, LocalDateTime modifiedat) {
        super(TempUser.TEMP_USER);

        setUserid(userid);
        setOtpid(otpid);
        setUsername(username);
        setFullname(fullname);
        setEmail(email);
        setStatus(status);
        setPassword(password);
        setSalt(salt);
        setCreatedby(createdby);
        setCreatedat(createdat);
        setModifiedby(modifiedby);
        setModifiedat(modifiedat);
    }

    /**
     * Getter for <code>authentication.temp_user.userId</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>authentication.temp_user.userId</code>.
     */
    public TempUserRecord setUserid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.otpId</code>.
     */
    public String getOtpid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>authentication.temp_user.otpId</code>.
     */
    public TempUserRecord setOtpid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>authentication.temp_user.username</code>.
     */
    public TempUserRecord setUsername(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.fullName</code>.
     */
    public String getFullname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>authentication.temp_user.fullName</code>.
     */
    public TempUserRecord setFullname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>authentication.temp_user.email</code>.
     */
    public TempUserRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>authentication.temp_user.status</code>.
     */
    public TempUserRecord setStatus(Byte value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.password</code>.
     */
    public byte[] getPassword() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>authentication.temp_user.password</code>.
     */
    public TempUserRecord setPassword(byte[] value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.salt</code>.
     */
    public byte[] getSalt() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>authentication.temp_user.salt</code>.
     */
    public TempUserRecord setSalt(byte[] value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.createdBy</code>.
     */
    public String getCreatedby() {
        return (String) get(8);
    }

    /**
     * Setter for <code>authentication.temp_user.createdBy</code>.
     */
    public TempUserRecord setCreatedby(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>authentication.temp_user.createdAt</code>.
     */
    public TempUserRecord setCreatedat(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>authentication.temp_user.modifiedBy</code>.
     */
    public String getModifiedby() {
        return (String) get(10);
    }

    /**
     * Setter for <code>authentication.temp_user.modifiedBy</code>.
     */
    public TempUserRecord setModifiedby(String value) {
        set(10, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>authentication.temp_user.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>authentication.temp_user.modifiedAt</code>.
     */
    public TempUserRecord setModifiedat(LocalDateTime value) {
        set(11, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row12<String, String, String, String, String, Byte, byte[], byte[], String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, String, String, String, Byte, byte[], byte[], String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TempUser.TEMP_USER.USERID;
    }

    @Override
    public Field<String> field2() {
        return TempUser.TEMP_USER.OTPID;
    }

    @Override
    public Field<String> field3() {
        return TempUser.TEMP_USER.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return TempUser.TEMP_USER.FULLNAME;
    }

    @Override
    public Field<String> field5() {
        return TempUser.TEMP_USER.EMAIL;
    }

    @Override
    public Field<Byte> field6() {
        return TempUser.TEMP_USER.STATUS;
    }

    @Override
    public Field<byte[]> field7() {
        return TempUser.TEMP_USER.PASSWORD;
    }

    @Override
    public Field<byte[]> field8() {
        return TempUser.TEMP_USER.SALT;
    }

    @Override
    public Field<String> field9() {
        return TempUser.TEMP_USER.CREATEDBY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return TempUser.TEMP_USER.CREATEDAT;
    }

    @Override
    public Field<String> field11() {
        return TempUser.TEMP_USER.MODIFIEDBY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return TempUser.TEMP_USER.MODIFIEDAT;
    }

    @Override
    public String component1() {
        return getUserid();
    }

    @Override
    public String component2() {
        return getOtpid();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getFullname();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public Byte component6() {
        return getStatus();
    }

    @Override
    public byte[] component7() {
        return getPassword();
    }

    @Override
    public byte[] component8() {
        return getSalt();
    }

    @Override
    public String component9() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedat();
    }

    @Override
    public String component11() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime component12() {
        return getModifiedat();
    }

    @Override
    public String value1() {
        return getUserid();
    }

    @Override
    public String value2() {
        return getOtpid();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getFullname();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public Byte value6() {
        return getStatus();
    }

    @Override
    public byte[] value7() {
        return getPassword();
    }

    @Override
    public byte[] value8() {
        return getSalt();
    }

    @Override
    public String value9() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedat();
    }

    @Override
    public String value11() {
        return getModifiedby();
    }

    @Override
    public LocalDateTime value12() {
        return getModifiedat();
    }

    @Override
    public TempUserRecord value1(String value) {
        setUserid(value);
        return this;
    }

    @Override
    public TempUserRecord value2(String value) {
        setOtpid(value);
        return this;
    }

    @Override
    public TempUserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public TempUserRecord value4(String value) {
        setFullname(value);
        return this;
    }

    @Override
    public TempUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TempUserRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public TempUserRecord value7(byte[] value) {
        setPassword(value);
        return this;
    }

    @Override
    public TempUserRecord value8(byte[] value) {
        setSalt(value);
        return this;
    }

    @Override
    public TempUserRecord value9(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public TempUserRecord value10(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public TempUserRecord value11(String value) {
        setModifiedby(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TempUserRecord value12(LocalDateTime value) {
        setModifiedat(value);
        return this;
    }

    @Override
    public TempUserRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, byte[] value7, byte[] value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }
}
