/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Password implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        userid;
    private byte[]        password;
    private byte[]        salt;
    private String        createdby;
    private LocalDateTime createdat;
    private String        modifiedby;
    private LocalDateTime modifiedat;

    public Password() {}

    public Password(Password value) {
        this.userid = value.userid;
        this.password = value.password;
        this.salt = value.salt;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
    }

    public Password(
        String        userid,
        byte[]        password,
        byte[]        salt,
        String        createdby,
        LocalDateTime createdat,
        String        modifiedby,
        LocalDateTime modifiedat
    ) {
        this.userid = userid;
        this.password = password;
        this.salt = salt;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>user.password.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>user.password.userId</code>.
     */
    public Password setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>user.password.password</code>.
     */
    public byte[] getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>user.password.password</code>.
     */
    public Password setPassword(byte[] password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>user.password.salt</code>.
     */
    public byte[] getSalt() {
        return this.salt;
    }

    /**
     * Setter for <code>user.password.salt</code>.
     */
    public Password setSalt(byte[] salt) {
        this.salt = salt;
        return this;
    }

    /**
     * Getter for <code>user.password.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>user.password.createdBy</code>.
     */
    public Password setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>user.password.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>user.password.createdAt</code>.
     */
    public Password setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>user.password.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>user.password.modifiedBy</code>.
     */
    public Password setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    /**
     * Getter for <code>user.password.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>user.password.modifiedAt</code>.
     */
    public Password setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Password (");

        sb.append(userid);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
