/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables;


import com.hieplp.recipe.auth.common.repository.generate.Authentication;
import com.hieplp.recipe.auth.common.repository.generate.Keys;
import com.hieplp.recipe.auth.common.repository.generate.tables.records.TempUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempUser extends TableImpl<TempUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>authentication.temp_user</code>
     */
    public static final TempUser TEMP_USER = new TempUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TempUserRecord> getRecordType() {
        return TempUserRecord.class;
    }

    /**
     * The column <code>authentication.temp_user.userId</code>.
     */
    public final TableField<TempUserRecord, String> USERID = createField(DSL.name("userId"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>authentication.temp_user.username</code>.
     */
    public final TableField<TempUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authentication.temp_user.fullName</code>.
     */
    public final TableField<TempUserRecord, String> FULLNAME = createField(DSL.name("fullName"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authentication.temp_user.email</code>.
     */
    public final TableField<TempUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authentication.temp_user.status</code>.
     */
    public final TableField<TempUserRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.defaultValue(DSL.inline("NULL", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>authentication.temp_user.password</code>.
     */
    public final TableField<TempUserRecord, byte[]> PASSWORD = createField(DSL.name("password"), SQLDataType.BINARY(64).defaultValue(DSL.inline("NULL", SQLDataType.BINARY)), this, "");

    /**
     * The column <code>authentication.temp_user.salt</code>.
     */
    public final TableField<TempUserRecord, byte[]> SALT = createField(DSL.name("salt"), SQLDataType.BINARY(64).defaultValue(DSL.inline("NULL", SQLDataType.BINARY)), this, "");

    /**
     * The column <code>authentication.temp_user.createdBy</code>.
     */
    public final TableField<TempUserRecord, String> CREATEDBY = createField(DSL.name("createdBy"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authentication.temp_user.createdAt</code>.
     */
    public final TableField<TempUserRecord, LocalDateTime> CREATEDAT = createField(DSL.name("createdAt"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>authentication.temp_user.modifiedBy</code>.
     */
    public final TableField<TempUserRecord, String> MODIFIEDBY = createField(DSL.name("modifiedBy"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authentication.temp_user.modifiedAt</code>.
     */
    public final TableField<TempUserRecord, LocalDateTime> MODIFIEDAT = createField(DSL.name("modifiedAt"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private TempUser(Name alias, Table<TempUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TempUser(Name alias, Table<TempUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>authentication.temp_user</code> table reference
     */
    public TempUser(String alias) {
        this(DSL.name(alias), TEMP_USER);
    }

    /**
     * Create an aliased <code>authentication.temp_user</code> table reference
     */
    public TempUser(Name alias) {
        this(alias, TEMP_USER);
    }

    /**
     * Create a <code>authentication.temp_user</code> table reference
     */
    public TempUser() {
        this(DSL.name("temp_user"), null);
    }

    public <O extends Record> TempUser(Table<O> child, ForeignKey<O, TempUserRecord> key) {
        super(child, key, TEMP_USER);
    }

    @Override
    public Schema getSchema() {
        return Authentication.AUTHENTICATION;
    }

    @Override
    public UniqueKey<TempUserRecord> getPrimaryKey() {
        return Keys.KEY_TEMP_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<TempUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TempUserRecord>>asList(Keys.KEY_TEMP_USER_PRIMARY);
    }

    @Override
    public TempUser as(String alias) {
        return new TempUser(DSL.name(alias), this);
    }

    @Override
    public TempUser as(Name alias) {
        return new TempUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TempUser rename(String name) {
        return new TempUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TempUser rename(Name name) {
        return new TempUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, String, String, Byte, byte[], byte[], String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
