/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.auth.common.repository.generate.tables.daos;


import com.hieplp.recipe.auth.common.repository.generate.tables.Otp;
import com.hieplp.recipe.auth.common.repository.generate.tables.records.OtpRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import java.time.LocalDateTime;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OtpDao extends DAOImpl<OtpRecord, com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp, String> {

    /**
     * Create a new OtpDao without any configuration
     */
    public OtpDao() {
        super(Otp.OTP, com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp.class);
    }

    /**
     * Create a new OtpDao with an attached configuration
     */
    public OtpDao(Configuration configuration) {
        super(Otp.OTP, com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp.class, configuration);
    }

    @Override
    public String getId(com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp object) {
        return object.getOtpid();
    }

    /**
     * Fetch records that have <code>otpId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfOtpid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Otp.OTP.OTPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>otpId IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByOtpid(String... values) {
        return fetch(Otp.OTP.OTPID, values);
    }

    /**
     * Fetch a unique record that has <code>otpId = value</code>
     */
    public com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp fetchOneByOtpid(String value) {
        return fetchOne(Otp.OTP.OTPID, value);
    }

    /**
     * Fetch records that have <code>sendTo BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfSendto(String lowerInclusive, String upperInclusive) {
        return fetchRange(Otp.OTP.SENDTO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sendTo IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchBySendto(String... values) {
        return fetch(Otp.OTP.SENDTO, values);
    }

    /**
     * Fetch records that have <code>otpCode BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfOtpcode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Otp.OTP.OTPCODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>otpCode IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByOtpcode(String... values) {
        return fetch(Otp.OTP.OTPCODE, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfType(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Otp.OTP.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByType(Byte... values) {
        return fetch(Otp.OTP.TYPE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Otp.OTP.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByStatus(Byte... values) {
        return fetch(Otp.OTP.STATUS, values);
    }

    /**
     * Fetch records that have <code>issuedAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfIssuedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Otp.OTP.ISSUEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>issuedAt IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByIssuedat(LocalDateTime... values) {
        return fetch(Otp.OTP.ISSUEDAT, values);
    }

    /**
     * Fetch records that have <code>expiredAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfExpiredat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Otp.OTP.EXPIREDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expiredAt IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByExpiredat(LocalDateTime... values) {
        return fetch(Otp.OTP.EXPIREDAT, values);
    }

    /**
     * Fetch records that have <code>createdAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfCreatedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Otp.OTP.CREATEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdAt IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByCreatedat(LocalDateTime... values) {
        return fetch(Otp.OTP.CREATEDAT, values);
    }

    /**
     * Fetch records that have <code>createdBy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Otp.OTP.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdBy IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByCreatedby(String... values) {
        return fetch(Otp.OTP.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>modifiedAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfModifiedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Otp.OTP.MODIFIEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedAt IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByModifiedat(LocalDateTime... values) {
        return fetch(Otp.OTP.MODIFIEDAT, values);
    }

    /**
     * Fetch records that have <code>modifiedBy BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchRangeOfModifiedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Otp.OTP.MODIFIEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedBy IN (values)</code>
     */
    public List<com.hieplp.recipe.auth.common.repository.generate.tables.pojos.Otp> fetchByModifiedby(String... values) {
        return fetch(Otp.OTP.MODIFIEDBY, values);
    }
}
