/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate;


import com.hieplp.recipe.user.common.repository.generate.tables.User;
import com.hieplp.recipe.user.common.repository.generate.tables.*;


/**
 * Convenience access to all tables in user.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>user.association_value_entry</code>.
     */
    public static final AssociationValueEntry ASSOCIATION_VALUE_ENTRY = AssociationValueEntry.ASSOCIATION_VALUE_ENTRY;

    /**
     * The table <code>user.dead_letter_entry</code>.
     */
    public static final DeadLetterEntry DEAD_LETTER_ENTRY = DeadLetterEntry.DEAD_LETTER_ENTRY;

    /**
     * The table <code>user.domain_event_entry</code>.
     */
    public static final DomainEventEntry DOMAIN_EVENT_ENTRY = DomainEventEntry.DOMAIN_EVENT_ENTRY;

    /**
     * The table <code>user.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>user.password</code>.
     */
    public static final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>user.saga_entry</code>.
     */
    public static final SagaEntry SAGA_ENTRY = SagaEntry.SAGA_ENTRY;

    /**
     * The table <code>user.snapshot_event_entry</code>.
     */
    public static final SnapshotEventEntry SNAPSHOT_EVENT_ENTRY = SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY;

    /**
     * The table <code>user.token_entry</code>.
     */
    public static final TokenEntry TOKEN_ENTRY = TokenEntry.TOKEN_ENTRY;

    /**
     * The table <code>user.user</code>.
     */
    public static final User USER_ = User.USER_;
}
