/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.records;


import com.hieplp.recipe.user.common.repository.generate.tables.AssociationValueEntry;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AssociationValueEntryRecord extends UpdatableRecordImpl<AssociationValueEntryRecord> implements Record5<Long, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached AssociationValueEntryRecord
     */
    public AssociationValueEntryRecord() {
        super(AssociationValueEntry.ASSOCIATION_VALUE_ENTRY);
    }

    /**
     * Create a detached, initialised AssociationValueEntryRecord
     */
    public AssociationValueEntryRecord(Long id, String associationKey, String associationValue, String sagaId, String sagaType) {
        super(AssociationValueEntry.ASSOCIATION_VALUE_ENTRY);

        setId(id);
        setAssociationKey(associationKey);
        setAssociationValue(associationValue);
        setSagaId(sagaId);
        setSagaType(sagaType);
    }

    /**
     * Getter for <code>user.association_value_entry.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user.association_value_entry.id</code>.
     */
    public AssociationValueEntryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.association_key</code>.
     */
    public String getAssociationKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.association_value_entry.association_key</code>.
     */
    public AssociationValueEntryRecord setAssociationKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.association_value</code>.
     */
    public String getAssociationValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.association_value_entry.association_value</code>.
     */
    public AssociationValueEntryRecord setAssociationValue(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user.association_value_entry.saga_id</code>.
     */
    public String getSagaId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.association_value_entry.saga_id</code>.
     */
    public AssociationValueEntryRecord setSagaId(String value) {
        set(3, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.association_value_entry.saga_type</code>.
     */
    public String getSagaType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.association_value_entry.saga_type</code>.
     */
    public AssociationValueEntryRecord setSagaType(String value) {
        set(4, value);
        return this;
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<Long, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.ID;
    }

    @Override
    public Field<String> field2() {
        return AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.ASSOCIATION_KEY;
    }

    @Override
    public Field<String> field3() {
        return AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.ASSOCIATION_VALUE;
    }

    @Override
    public Field<String> field4() {
        return AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.SAGA_ID;
    }

    @Override
    public Field<String> field5() {
        return AssociationValueEntry.ASSOCIATION_VALUE_ENTRY.SAGA_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAssociationKey();
    }

    @Override
    public String component3() {
        return getAssociationValue();
    }

    @Override
    public String component4() {
        return getSagaId();
    }

    @Override
    public String component5() {
        return getSagaType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAssociationKey();
    }

    @Override
    public String value3() {
        return getAssociationValue();
    }

    @Override
    public String value4() {
        return getSagaId();
    }

    @Override
    public String value5() {
        return getSagaType();
    }

    @Override
    public AssociationValueEntryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AssociationValueEntryRecord value2(String value) {
        setAssociationKey(value);
        return this;
    }

    @Override
    public AssociationValueEntryRecord value3(String value) {
        setAssociationValue(value);
        return this;
    }

    @Override
    public AssociationValueEntryRecord value4(String value) {
        setSagaId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AssociationValueEntryRecord value5(String value) {
        setSagaType(value);
        return this;
    }

    @Override
    public AssociationValueEntryRecord values(Long value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
