/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.records;


import com.hieplp.recipe.user.common.repository.generate.tables.DomainEventEntry;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DomainEventEntryRecord extends UpdatableRecordImpl<DomainEventEntryRecord> implements Record10<Long, String, byte[], byte[], String, String, String, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached DomainEventEntryRecord
     */
    public DomainEventEntryRecord() {
        super(DomainEventEntry.DOMAIN_EVENT_ENTRY);
    }

    /**
     * Create a detached, initialised DomainEventEntryRecord
     */
    public DomainEventEntryRecord(Long globalIndex, String eventIdentifier, byte[] metaData, byte[] payload, String payloadRevision, String payloadType, String timeStamp, String aggregateIdentifier, Long sequenceNumber, String type) {
        super(DomainEventEntry.DOMAIN_EVENT_ENTRY);

        setGlobalIndex(globalIndex);
        setEventIdentifier(eventIdentifier);
        setMetaData(metaData);
        setPayload(payload);
        setPayloadRevision(payloadRevision);
        setPayloadType(payloadType);
        setTimeStamp(timeStamp);
        setAggregateIdentifier(aggregateIdentifier);
        setSequenceNumber(sequenceNumber);
        setType(type);
    }

    /**
     * Getter for <code>user.domain_event_entry.global_index</code>.
     */
    public Long getGlobalIndex() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user.domain_event_entry.global_index</code>.
     */
    public DomainEventEntryRecord setGlobalIndex(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.event_identifier</code>.
     */
    public String getEventIdentifier() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.domain_event_entry.event_identifier</code>.
     */
    public DomainEventEntryRecord setEventIdentifier(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.meta_data</code>.
     */
    public byte[] getMetaData() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>user.domain_event_entry.meta_data</code>.
     */
    public DomainEventEntryRecord setMetaData(byte[] value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload</code>.
     */
    public byte[] getPayload() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>user.domain_event_entry.payload</code>.
     */
    public DomainEventEntryRecord setPayload(byte[] value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload_revision</code>.
     */
    public String getPayloadRevision() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user.domain_event_entry.payload_revision</code>.
     */
    public DomainEventEntryRecord setPayloadRevision(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.payload_type</code>.
     */
    public String getPayloadType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user.domain_event_entry.payload_type</code>.
     */
    public DomainEventEntryRecord setPayloadType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.time_stamp</code>.
     */
    public String getTimeStamp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user.domain_event_entry.time_stamp</code>.
     */
    public DomainEventEntryRecord setTimeStamp(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.aggregate_identifier</code>.
     */
    public String getAggregateIdentifier() {
        return (String) get(7);
    }

    /**
     * Setter for <code>user.domain_event_entry.aggregate_identifier</code>.
     */
    public DomainEventEntryRecord setAggregateIdentifier(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>user.domain_event_entry.sequence_number</code>.
     */
    public Long getSequenceNumber() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>user.domain_event_entry.sequence_number</code>.
     */
    public DomainEventEntryRecord setSequenceNumber(Long value) {
        set(8, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.domain_event_entry.type</code>.
     */
    public String getType() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.domain_event_entry.type</code>.
     */
    public DomainEventEntryRecord setType(String value) {
        set(9, value);
        return this;
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row10<Long, String, byte[], byte[], String, String, String, String, Long, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, byte[], byte[], String, String, String, String, Long, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.GLOBAL_INDEX;
    }

    @Override
    public Field<String> field2() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.EVENT_IDENTIFIER;
    }

    @Override
    public Field<byte[]> field3() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.META_DATA;
    }

    @Override
    public Field<byte[]> field4() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.PAYLOAD;
    }

    @Override
    public Field<String> field5() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.PAYLOAD_REVISION;
    }

    @Override
    public Field<String> field6() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.PAYLOAD_TYPE;
    }

    @Override
    public Field<String> field7() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.TIME_STAMP;
    }

    @Override
    public Field<String> field8() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.AGGREGATE_IDENTIFIER;
    }

    @Override
    public Field<Long> field9() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.SEQUENCE_NUMBER;
    }

    @Override
    public Field<String> field10() {
        return DomainEventEntry.DOMAIN_EVENT_ENTRY.TYPE;
    }

    @Override
    public Long component1() {
        return getGlobalIndex();
    }

    @Override
    public String component2() {
        return getEventIdentifier();
    }

    @Override
    public byte[] component3() {
        return getMetaData();
    }

    @Override
    public byte[] component4() {
        return getPayload();
    }

    @Override
    public String component5() {
        return getPayloadRevision();
    }

    @Override
    public String component6() {
        return getPayloadType();
    }

    @Override
    public String component7() {
        return getTimeStamp();
    }

    @Override
    public String component8() {
        return getAggregateIdentifier();
    }

    @Override
    public Long component9() {
        return getSequenceNumber();
    }

    @Override
    public String component10() {
        return getType();
    }

    @Override
    public Long value1() {
        return getGlobalIndex();
    }

    @Override
    public String value2() {
        return getEventIdentifier();
    }

    @Override
    public byte[] value3() {
        return getMetaData();
    }

    @Override
    public byte[] value4() {
        return getPayload();
    }

    @Override
    public String value5() {
        return getPayloadRevision();
    }

    @Override
    public String value6() {
        return getPayloadType();
    }

    @Override
    public String value7() {
        return getTimeStamp();
    }

    @Override
    public String value8() {
        return getAggregateIdentifier();
    }

    @Override
    public Long value9() {
        return getSequenceNumber();
    }

    @Override
    public String value10() {
        return getType();
    }

    @Override
    public DomainEventEntryRecord value1(Long value) {
        setGlobalIndex(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value2(String value) {
        setEventIdentifier(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value3(byte[] value) {
        setMetaData(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value4(byte[] value) {
        setPayload(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value5(String value) {
        setPayloadRevision(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value6(String value) {
        setPayloadType(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value7(String value) {
        setTimeStamp(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value8(String value) {
        setAggregateIdentifier(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord value9(Long value) {
        setSequenceNumber(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public DomainEventEntryRecord value10(String value) {
        setType(value);
        return this;
    }

    @Override
    public DomainEventEntryRecord values(Long value1, String value2, byte[] value3, byte[] value4, String value5, String value6, String value7, String value8, Long value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
