/*
 * This file is generated by jOOQ.
 */
package com.hieplp.recipe.user.common.repository.generate.tables.records;


import com.hieplp.recipe.user.common.repository.generate.tables.SnapshotEventEntry;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SnapshotEventEntryRecord extends UpdatableRecordImpl<SnapshotEventEntryRecord> implements Record9<String, Long, String, String, byte[], byte[], String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached SnapshotEventEntryRecord
     */
    public SnapshotEventEntryRecord() {
        super(SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY);
    }

    /**
     * Create a detached, initialised SnapshotEventEntryRecord
     */
    public SnapshotEventEntryRecord(String aggregateIdentifier, Long sequenceNumber, String type, String eventIdentifier, byte[] metaData, byte[] payload, String payloadRevision, String payloadType, String timeStamp) {
        super(SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY);

        setAggregateIdentifier(aggregateIdentifier);
        setSequenceNumber(sequenceNumber);
        setType(type);
        setEventIdentifier(eventIdentifier);
        setMetaData(metaData);
        setPayload(payload);
        setPayloadRevision(payloadRevision);
        setPayloadType(payloadType);
        setTimeStamp(timeStamp);
    }

    /**
     * Getter for <code>user.snapshot_event_entry.aggregate_identifier</code>.
     */
    public String getAggregateIdentifier() {
        return (String) get(0);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.aggregate_identifier</code>.
     */
    public SnapshotEventEntryRecord setAggregateIdentifier(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.sequence_number</code>.
     */
    public Long getSequenceNumber() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.sequence_number</code>.
     */
    public SnapshotEventEntryRecord setSequenceNumber(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.type</code>.
     */
    public SnapshotEventEntryRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.event_identifier</code>.
     */
    public String getEventIdentifier() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.event_identifier</code>.
     */
    public SnapshotEventEntryRecord setEventIdentifier(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.meta_data</code>.
     */
    public byte[] getMetaData() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.meta_data</code>.
     */
    public SnapshotEventEntryRecord setMetaData(byte[] value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.payload</code>.
     */
    public byte[] getPayload() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.payload</code>.
     */
    public SnapshotEventEntryRecord setPayload(byte[] value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.payload_revision</code>.
     */
    public String getPayloadRevision() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.payload_revision</code>.
     */
    public SnapshotEventEntryRecord setPayloadRevision(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user.snapshot_event_entry.payload_type</code>.
     */
    public String getPayloadType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>user.snapshot_event_entry.payload_type</code>.
     */
    public SnapshotEventEntryRecord setPayloadType(String value) {
        set(7, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>user.snapshot_event_entry.time_stamp</code>.
     */
    public String getTimeStamp() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>user.snapshot_event_entry.time_stamp</code>.
     */
    public SnapshotEventEntryRecord setTimeStamp(String value) {
        set(8, value);
        return this;
    }

    @Override
    public Record3<String, Long, String> key() {
        return (Record3) super.key();
    }

    @Override
    public Row9<String, Long, String, String, byte[], byte[], String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, Long, String, String, byte[], byte[], String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.AGGREGATE_IDENTIFIER;
    }

    @Override
    public Field<Long> field2() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.SEQUENCE_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.TYPE;
    }

    @Override
    public Field<String> field4() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.EVENT_IDENTIFIER;
    }

    @Override
    public Field<byte[]> field5() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.META_DATA;
    }

    @Override
    public Field<byte[]> field6() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.PAYLOAD;
    }

    @Override
    public Field<String> field7() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.PAYLOAD_REVISION;
    }

    @Override
    public Field<String> field8() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.PAYLOAD_TYPE;
    }

    @Override
    public Field<String> field9() {
        return SnapshotEventEntry.SNAPSHOT_EVENT_ENTRY.TIME_STAMP;
    }

    @Override
    public String component1() {
        return getAggregateIdentifier();
    }

    @Override
    public Long component2() {
        return getSequenceNumber();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getEventIdentifier();
    }

    @Override
    public byte[] component5() {
        return getMetaData();
    }

    @Override
    public byte[] component6() {
        return getPayload();
    }

    @Override
    public String component7() {
        return getPayloadRevision();
    }

    @Override
    public String component8() {
        return getPayloadType();
    }

    @Override
    public String component9() {
        return getTimeStamp();
    }

    @Override
    public String value1() {
        return getAggregateIdentifier();
    }

    @Override
    public Long value2() {
        return getSequenceNumber();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getEventIdentifier();
    }

    @Override
    public byte[] value5() {
        return getMetaData();
    }

    @Override
    public byte[] value6() {
        return getPayload();
    }

    @Override
    public String value7() {
        return getPayloadRevision();
    }

    @Override
    public String value8() {
        return getPayloadType();
    }

    @Override
    public String value9() {
        return getTimeStamp();
    }

    @Override
    public SnapshotEventEntryRecord value1(String value) {
        setAggregateIdentifier(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value2(Long value) {
        setSequenceNumber(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value4(String value) {
        setEventIdentifier(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value5(byte[] value) {
        setMetaData(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value6(byte[] value) {
        setPayload(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value7(String value) {
        setPayloadRevision(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord value8(String value) {
        setPayloadType(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public SnapshotEventEntryRecord value9(String value) {
        setTimeStamp(value);
        return this;
    }

    @Override
    public SnapshotEventEntryRecord values(String value1, Long value2, String value3, String value4, byte[] value5, byte[] value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
